# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_model <- function(data, k, sigma, lambda, z, burnin, sample) {
    .Call('RcppMixtureModel_run_model', PACKAGE = 'RcppMixtureModel', data, k, sigma, lambda, z, burnin, sample)
}

rmultinom_cpp <- function(n, p) {
    .Call('RcppMixtureModel_rmultinom_cpp', PACKAGE = 'RcppMixtureModel', n, p)
}

rz_cpp <- function(n, k) {
    .Call('RcppMixtureModel_rz_cpp', PACKAGE = 'RcppMixtureModel', n, k)
}

