# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_model <- function(data, k, sigma, lambda, z, burnin, sample) {
    .Call('RcppMixtureModel_run_model', PACKAGE = 'RcppMixtureModel', data, k, sigma, lambda, z, burnin, sample)
}

